export const meta = {
  name: 'r27-t63-memdep',
  description: 'Opus builds t63_memdep (the MEM_IN_STRUCT_P access-spelling generator) with a fixture-backed evaluation; an opus reviewer refutes; implementer fixes',
  phases: [
    { title: 'Implement', detail: 'generator + unit tests + near-band evaluation' },
    { title: 'Review', detail: 'adversarial reviewer reruns everything' },
    { title: 'Fix', detail: 'confirmed defects fixed' },
  ],
}

const RULES = `
Repository: <repo> (run everything from there). Read docs/LANE_KIT.md, tools/xform/t57_keepafterstore.py (the generator contract: class T with name/level/needs_verify, eligible(text,row,census), apply_verified(text,row,census,vf)), tools/xform/natural.py (menu generators: *_candidates(text) -> [(label, text)]), tools/xform/screen.py (compile_s/sdiff, the free cc1 screen), tools/pin_search_engine.py (improves(), mechanism(), how menus are consumed), tools/pin_census.py (sites_of), tools/pin_sites.py (erase_many), tools/lane_eval.py (--help).
HARD RULES: never write under src/, ledger/, config/, build_ovl/; never run sweep.py, gates, pin_search.py, apply_candidates.py, land_lanes.sh, launch_lane.sh, codex or agy; never run state-changing git. The IO discipline in CLAUDE.md applies: no recursive search over work/ or the repo root; grep only tools/, include/, docs/, and toolchain/gcc-src/<one version>/ with --max-filesize 4M. Write only under tools/xform/, tools/tests/, tools/fixtures/, and your lane directory work/native_lane/t63_dev/ (create it, with a .ignore file containing "*" in its scratch/ and tmp/). At most 8 compiles at a time (lane_eval --jobs 6). Other jobs are running on the machine (a background allocator probe, another workflow): do not kill or wait on any process you did not start. No scaffolding may ever appear in a candidate: no new ASM_* macro, __asm__, volatile, fake dependency, do{}while(0), while(0), for(;0;) or other one-trip block, no new #pragma or attribute. A candidate must compile at the row's cell and must be a pure spelling change with IDENTICAL address arithmetic.`

const MECHANISM = `THE MECHANISM (proven this session, tools/fixtures/memdep/run.sh - run it first and read tools/fixtures/memdep/memdep.c):
gcc 2.7.2 sched.c lines 815-880 (true_dependence, anti_dependence, output_dependence; byte-identical in 2.8.1 sched.c ~849; toolchain/gcc-src/<ver>/sched.c) treat two memory references that memrefs_conflict_p cannot separate as INDEPENDENT when one is a struct-member access through a VARYING address (MEM_IN_STRUCT_P set, mode not QImode) and the other is a NON-struct access at a FIXED address (rtx_addr_varies_p false: a bare global scalar via a SYMBOL_REF, or a stack slot via the frame/stack pointer). cse.c (invalidate, ~line 7571) and loop.c (~2682) consult MEM_IN_STRUCT_P the same way, so the flag also decides which loads CSE keeps across a store and what loop.c treats as invariant. MEM_IN_STRUCT_P is set by expand_expr for COMPONENT_REF (p->f, s.f), ARRAY_REF (a[i], G[0]) and for INDIRECT_REF of an aggregate type; a plain scalar VAR_DECL (extern s32 G; ... G) and a cast dereference (*(s32 *)((u8 *)p + 8), M2C_FIELD) are NOT in-struct. rtx_addr_varies_p (rtlanal.c 163): a SYMBOL_REF+const is fixed; anything holding a non-fixed register varies. Fixture result in every stock cell except 2.91.66: shapes A (p->a = v; return G;), F (short member) and G (G = v; return p->a;) emit the LOAD FIRST (the exemption fired and the scheduler hoisted the load over the store); B (the same store spelled *(int *)((char *)p + 0)), C (G spelled H[0]), D (G spelled GS.x), E (a u8 member: QImode never exempt) and H keep store-then-load. So the SPELLING of one access - member vs cast, scalar global vs one-element array vs struct member - changes instruction order, surviving loads and hoisting while the emitted address arithmetic is identical. This class has never been tested in 26 rounds and no generator flips a spelling. Pinned rows hold 4,215 raw-cast accesses (*(T *)((u8 *)p + off), M2C_FIELD) in 577 rows / 3,835 pins; 244 keeps have one within 4 lines; 43% of near-band pin residues are pure scheduling (same instructions, one moved).`

const SPEC = `BUILD tools/xform/t63_memdep.py, the access-spelling generator, in the contract of t57 (class T, name "t63_memdep", level 1, needs_verify True) AND exposing memdep_candidates(text) -> [(label, text)] for the search menu (bounded to 48 candidates, the single-access flips nearest a pin site first).
FLIPS (each must keep the address arithmetic identical; the screen and vf decide; nothing else is asserted):
 1. member -> cast: p->f, (*p).f, ((S *)p)->f, p->f.g, s.f where the base is a pointer or a local: rewrite to *(T *)((u8 *)base + OFF) with T the member's declared type and OFF its byte offset. Resolve T and OFF from struct declarations visible in the row's file (the local S_xxx structs and typedefs, union views as in include/records/*.h) and from include/records/*.h and include/common.h/game.h when the type name is found there; when a member name carries its offset (unk_XX, at_XX, pad_XX) you may cross-check but the declaration decides; skip an access you cannot resolve (record the reason in the journal). Nested members: sum the offsets. Bitfields, arrays of structs with a variable index and members of array type: skip. A struct-typed access (whole struct copy) is skipped.
 2. cast -> member: *(T *)((u8 *)p + OFF) and M2C_FIELD(p, T *, OFF) (include/m2c_compat.h) rewritten to ((S *)p)->m when a struct S visible to the row has a member m of type T at offset OFF (prefer a struct the row already uses for p; else any visible struct with that member; else skip - do NOT invent struct types).
 3. global scalar <-> one-element array, only for globals the row's own file declares with extern: 'extern T G;' with uses G / &G -> 'extern T G[1];' with uses G[0] / G (address: &G[0] or G) and the reverse when every use is G[0] or &G[0]. Keep the declaration and every use consistent; a global that any include declares is skipped.
 4. array element <-> cast for a global array with a CONSTANT index: G[k] <-> *(T *)((u8 *)G + k*sizeof(T)) (skip when the element type is unknown).
Byte-typed accesses (u8/s8) are never exempt in sched but may matter in cse: try them last.
CANDIDATES per row: for each live ASM_* site (sites_of), the accesses within 8 lines; (a) each access flipped alone; (b) every access of the same base pointer / global in the whole function flipped together (retail's author spelled one pointer one way); each candidate is tried with the nearest pin erased (erase_many, clean_notes=True), then, if the row has 2-3 pins within the window, with all of them erased. Screen every candidate with compile_s/sdiff against the current text's listing (the pinned text is byte-exact, so distance 0 means identical cc1 output); call vf only on distance-0 candidates that pass pin_search_engine.improves (fewer pins, no more fences or fake deps). Budgets: T63_SCREENS (default 600) screens and T63_VERIFY (default 6) vf calls per row, journaled like t53 (pins_in, pins_out, screened, tried, candidates_n, nearest distances, step labels, skip reasons). Restart on the new text after a win.
TESTS: tools/tests/test_t63_memdep.py with synthetic texts covering each flip direction, nested members, union views (include/records style at00_s32 etc.), the M2C_FIELD macro, a global declared in an include (must be skipped), an unresolvable member (skipped, reason recorded), and a check that a flipped text and its original compile to listings whose non-order-sensitive multiset of instructions is identical for a simple shape (use tools/xform/screen.py on a fake row dict like {"cfg": "2.7.2", "kind": "overlay", ...} - read compile_s to see what it needs).
EVALUATE with tools/lane_eval.py --lane work/native_lane/t63_dev --module tools/xform/t63_memdep.py --jobs 6, on two row lists: <scratchpad>/nearband_keep_rows.txt (140 rows whose keep erasure is within 4 asm lines; tag t63_keep) and the first 60 rows of .../scratchpad/nearband_rows.txt (tag t63_near). Report: rows eligible, candidates generated per row (median), screened, exact outputs (row ids, pins before/after, the flip label), and for 10 misses the nearest distance and what the residue looks like. If the exact count is zero, investigate three near-misses by hand (compile with -da through tools/xform/sched_trace.py and read the sched dump) and report what the dependence graph shows - a bounded negative with a reason is a valid result.
Do not touch tools/sweep.py, pin_search_engine.py or land_lanes.sh (I integrate after review). Return: file paths, the test run output, the two evaluation tables verbatim, and every skip-reason count.`

const VERDICT = {
  type: 'object',
  properties: {
    defects: { type: 'array', items: { type: 'object', properties: {
      severity: { type: 'string', enum: ['blocking', 'major', 'minor'] },
      where: { type: 'string' }, what: { type: 'string' }, evidence: { type: 'string' } },
      required: ['severity', 'where', 'what', 'evidence'] } },
    exact_rows_confirmed: { type: 'integer' },
    summary: { type: 'string' },
  },
  required: ['defects', 'exact_rows_confirmed', 'summary'],
}

const impl = await agent(`${RULES}\n\n${MECHANISM}\n\nYOUR TASK (implementer): ${SPEC}`,
  { label: 'impl:t63', phase: 'Implement', model: 'opus', effort: 'high' })

const review = await agent(`${RULES}\n\n${MECHANISM}\n\nYOU ARE THE ADVERSARIAL REVIEWER of tools/xform/t63_memdep.py, just built by another agent to this spec:\n${SPEC}\n\nThe implementer's report:\n${impl}\n\nRefute it. Read the generator in full. Run its unit tests. For five of its candidates on real rows (take them from work/native_lane/t63_dev/), compile the original and the candidate through tools/xform/screen.py and prove the address arithmetic is identical (same base registers and offsets in every load/store) - any candidate that changes an offset, a width, a signedness, or a symbol is a BLOCKING defect. Check that no candidate adds scaffolding (grep the out/ files for ASM_, volatile, __asm__, while (0)). Check the struct resolution against three real structs (one local S_xxx, one include/records union view, one nested member) by hand. Check budget accounting (screened/tried never exceed the limits), that eligible() refuses rows with asm_blocker, that a win restarts on the new text, and that the journal's skip reasons add up. Re-run lane_eval on 20 rows of your own choice from .../scratchpad/nearband_rows.txt (rows 61-80) with a new tag and report its exact count independently. Do not fix anything. Return only defects you demonstrated with evidence, and the exact-row count you confirmed by reading vf results yourself.`,
  { label: 'review:t63', phase: 'Review', model: 'opus', effort: 'high', schema: VERDICT })

const real = (review?.defects || []).filter(d => d.severity !== 'minor')
let fix = 'no blocking or major defects'
if (real.length) {
  fix = await agent(`${RULES}\n\n${MECHANISM}\n\nYou implemented tools/xform/t63_memdep.py (spec: ${SPEC}).\n\nAn adversarial reviewer demonstrated these defects:\n${JSON.stringify(real, null, 2)}\n\nFix each one (or show with evidence that the reviewer is wrong), rerun the unit tests and the t63_keep evaluation (tag t63_keep2), and return the updated tables and a per-defect note: fixed / disputed (with evidence).`,
    { label: 'fix:t63', phase: 'Fix', model: 'opus', effort: 'high' })
}
return { impl, review, fix }