#!/usr/bin/env python3
"""Regenerate src/<container>/INDEX.md from the ledger: one row per function with its CURRENT recipe.

    python3 tools/gen_src_index.py            # all containers (also run by tools/status.py)

Columns: file | function | bytes | compiler | level | module | pins.  `compiler` is ledger/rows.jsonl `cfg` (the
recipe the row is gated at), `level` ledger/levels.jsonl, `module` ledger/modules.jsonl, `pins` the live pin sites
of the src text.  Until 2026-10-01 these files were written once at import (061b85f8d) and never refreshed: 4,271 of
6,756 compiler cells were stale after rounds 55-84 moved recipes.
"""
import collections
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from common import rows, LEDGER, read_jsonl  # noqa: E402
from pin_census import sites_of  # noqa: E402


def main():
    lev = {r["id"]: r.get("level") for r in read_jsonl(LEDGER / "levels.jsonl")}
    mod = {r["id"]: r.get("module", "") for r in read_jsonl(LEDGER / "modules.jsonl")}
    by = collections.defaultdict(list)
    for r in rows():
        by[r["id"].split("/")[0]].append(r)
    for c, rs in sorted(by.items()):
        d = ROOT / "src" / c
        if not (d / "INDEX.md").exists():
            continue
        out = [f"# {c}: {len(rs)} rows", "",
               "Generated by tools/gen_src_index.py from the ledger (recipe = ledger/rows.jsonl cfg); do not edit by hand.", "",
               "| file | function | bytes | compiler | level | module | pins |", "|---|---|---:|---|---:|---|---:|"]
        for r in sorted(rs, key=lambda r: r["id"]):
            name = r["id"].split("/", 1)[1]
            p = d / f"{name}.c"
            pins = len(list(sites_of(p.read_text(errors="replace")))) if p.exists() else ""
            lv = lev.get(r["id"])
            out.append(f"| {name}.c | {name} | {r.get('size', '')} | {r['cfg']} | {'' if lv is None else lv} | "
                       f"{mod.get(r['id'], '')} | {pins} |")
        (d / "INDEX.md").write_text("\n".join(out) + "\n")
        print(f"{c}: {len(rs)} rows")


if __name__ == "__main__":
    main()
